/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it19014500;

//import static com.sun.corba.se.spi.presentation.rmi.StubAdapter.request;
//import com.sun.xml.internal.ws.streaming.XMLStreamReaderUtil;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
//import Important Libraries
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author it19014500
 */
public class AddWorkingDetail extends javax.swing.JFrame {

    /**
     * Creates new form AddWorkingDetail
     */
    Integer tot = 00;
    
    public AddWorkingDetail() {
        initComponents();
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addWeek = new javax.swing.JComboBox<>();
        addMonth = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        addWd = new javax.swing.JComboBox<>();
        addMonday = new javax.swing.JCheckBox();
        addTuesday = new javax.swing.JCheckBox();
        addWednesday = new javax.swing.JCheckBox();
        addThursday = new javax.swing.JCheckBox();
        addFriday = new javax.swing.JCheckBox();
        addSaturday = new javax.swing.JCheckBox();
        addSunday = new javax.swing.JCheckBox();
        addHours = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        addMinutes = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        errorCompared = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        IdentifyKey = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(247, 250, 222));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(3, 48, 118));
        jLabel1.setText("ADD WORKING DAYS AND HOURS");

        jPanel3.setBackground(new java.awt.Color(176, 223, 236));

        jPanel2.setBackground(new java.awt.Color(212, 233, 221));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("VIEW");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 78, 99));
        jLabel2.setText("Month");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 78, 99));
        jLabel3.setText("Week");

        addWeek.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05" }));
        addWeek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addWeekActionPerformed(evt);
            }
        });

        addMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        addMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMonthActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 78, 99));
        jLabel4.setText("Number of Working Days");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 78, 99));
        jLabel5.setText("Working Days");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 78, 99));
        jLabel6.setText("Working Time Per Day");

        addWd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07" }));

        addMonday.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        addMonday.setText("Monday");
        addMonday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMondayMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMondayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMondayMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addMondayMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                addMondayMouseReleased(evt);
            }
        });
        addMonday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMondayActionPerformed(evt);
            }
        });

        addTuesday.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        addTuesday.setText("Tuesday");
        addTuesday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addTuesdayMouseClicked(evt);
            }
        });
        addTuesday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTuesdayActionPerformed(evt);
            }
        });

        addWednesday.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        addWednesday.setText("Wednesday");
        addWednesday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addWednesdayMouseClicked(evt);
            }
        });

        addThursday.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        addThursday.setText("Thursday");
        addThursday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addThursdayMouseClicked(evt);
            }
        });
        addThursday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addThursdayActionPerformed(evt);
            }
        });

        addFriday.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        addFriday.setText("Friday");
        addFriday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addFridayMouseClicked(evt);
            }
        });
        addFriday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFridayActionPerformed(evt);
            }
        });

        addSaturday.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        addSaturday.setText("Saturday");
        addSaturday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addSaturdayMouseClicked(evt);
            }
        });

        addSunday.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        addSunday.setText("Sunday");
        addSunday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addSundayMouseClicked(evt);
            }
        });

        addHours.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        addHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHoursActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Hours");

        addMinutes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "05", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55" }));
        addMinutes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMinutesActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Minutes");

        jButton3.setBackground(new java.awt.Color(182, 4, 45));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("RESET");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 153));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("ADD");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        errorCompared.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        errorCompared.setForeground(new java.awt.Color(0, 0, 102));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 78, 99));
        jLabel9.setText("Identification Key");

        IdentifyKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdentifyKeyActionPerformed(evt);
            }
        });

        jToggleButton1.setText("DASH BOARD");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addWd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(addMonday)
                                            .addComponent(addFriday))
                                        .addGap(42, 42, 42))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(addHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel7)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(addMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(addSaturday)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(addMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel8))
                                            .addComponent(addTuesday))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(addSunday)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                        .addComponent(addWednesday)
                                                        .addGap(37, 37, 37))
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jLabel9)
                                                        .addGap(11, 11, 11)))
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(IdentifyKey, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(addThursday))))
                                        .addContainerGap(35, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addComponent(jLabel3)
                                                .addGap(27, 27, 27)
                                                .addComponent(addWeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(75, 75, 75)
                                                .addComponent(jButton3)))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(errorCompared, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToggleButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jToggleButton1))
                    .addComponent(errorCompared))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addWeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(addMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(addWd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(IdentifyKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addMonday)
                        .addComponent(addTuesday)
                        .addComponent(addWednesday)
                        .addComponent(addThursday)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addFriday)
                    .addComponent(addSaturday)
                    .addComponent(addSunday))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(addHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(addMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addGap(37, 37, 37))
        );

        jToggleButton2.setText("Consecutive");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jToggleButton3.setText("Sessions");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        jToggleButton4.setText("Not Available Times");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        jToggleButton5.setText("Add Location");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });

        jToggleButton6.setBackground(new java.awt.Color(102, 255, 102));
        jToggleButton6.setText("Add Total Time Period");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToggleButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton6)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton2)
                    .addComponent(jToggleButton3)
                    .addComponent(jToggleButton4)
                    .addComponent(jToggleButton5)
                    .addComponent(jToggleButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Code for Close Event
    public void close(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // View Button:
        if(evt.getActionCommand().equals("VIEW")){
            System.out.println("Details Page of Working Days");
        }
        close();
        ViewWorkingDetail wd = new ViewWorkingDetail();
        wd.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addWeekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addWeekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addWeekActionPerformed

    private void addMondayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMondayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addMondayActionPerformed

    private void addHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addHoursActionPerformed

    private void addMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addMonthActionPerformed

    private void addMinutesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMinutesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addMinutesActionPerformed

    private void addThursdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addThursdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addThursdayActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // ADD Button:
        
        try{
            //Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            //String url = "jdbc:sqlserver://localhost:1433;databaseName=jayamadhuka;user=sa;password=root";
            //Connection conn = DriverManager.getConnection(url);
            //String wdi = "insert into workingdayshours(monDay,tuesDay,wednesDay,thursDay,friDay,saturDay,sunDay,hours,minuits,totDay,week,month,id) values(?,?,?,?,?,?,?,?,?,?,?,?,?)";
            //PreparedStatement pstmt = conn.prepareStatement(wdi);
            //Apache connection
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/ltdmgdb?zeroDateTimeBehavior=convertToNull","root","");
            String wdi = "insert into workingdayshours(monDay,tuesDay,wednesDay,thursDay,friDay,saturDay,sunDay,hours,minuits,totDay,week,month,id) values(?,?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement pstmt = c.prepareStatement(wdi);
            //String wdt ="insert into days(workingDay,idwd)values(?,?)";
            //PreparedStatement pstm = c.prepareStatement(wdt);
            

            
            String days1 = "No";
            String days2 = "No";
            String days3 = "No";
            String days4 = "No";
            String days5 = "No";
            String days6 = "No";
            String days7 = "No";
            String hours = "";
            String minuts = "";
            String week = "";
            String month = "";
            //int pk1=0;
            tot = 0;
            
            

                    
            if(addMonday.isSelected()){
                days1 = "Working";
                tot+=1;
                Connection d = DriverManager.getConnection("jdbc:mysql://localhost:3306/ltdmgdb?zeroDateTimeBehavior=convertToNull","root","");
                String wdt ="insert into days(workingDay,idwd)values(?,?)";
                PreparedStatement pstm = d.prepareStatement(wdt);
                String da1="MonDay";
                pstm.setString(1, da1);
                pstm.setInt(2, Integer.valueOf(IdentifyKey.getText()));
                pstm.executeUpdate();
            }
            else if(!(addMonday.isSelected())){
                Connection d = DriverManager.getConnection("jdbc:mysql://localhost:3306/ltdmgdb?zeroDateTimeBehavior=convertToNull","root","");
                String wdt ="insert into days(workingDay,idwd)values(?,?)";
                PreparedStatement pstm = d.prepareStatement(wdt);
                String da1="No MonDay";
                pstm.setString(1, da1);
                pstm.setInt(2, Integer.valueOf(IdentifyKey.getText()));
                pstm.executeUpdate();
            }
            if(addTuesday.isSelected()){
                days2 = "Working";
                tot+=1;
                Connection d = DriverManager.getConnection("jdbc:mysql://localhost:3306/ltdmgdb?zeroDateTimeBehavior=convertToNull","root","");
                String wdt ="insert into days(workingDay,idwd)values(?,?)";
                PreparedStatement pstm = d.prepareStatement(wdt);
                String da2="TuesDay";
                pstm.setString(1, da2);
                pstm.setInt(2, Integer.valueOf(IdentifyKey.getText()));
                pstm.executeUpdate();
                
            }
            else if(!(addTuesday.isSelected())){
                Connection d = DriverManager.getConnection("jdbc:mysql://localhost:3306/ltdmgdb?zeroDateTimeBehavior=convertToNull","root","");
                String wdt ="insert into days(workingDay,idwd)values(?,?)";
                PreparedStatement pstm = d.prepareStatement(wdt);
                String da2="No TuesDay";
                pstm.setString(1, da2);
                pstm.setInt(2, Integer.valueOf(IdentifyKey.getText()));
                pstm.executeUpdate();
            }
            if(addWednesday.isSelected()){
                days3 = "Working";
                tot+=1;
                Connection d = DriverManager.getConnection("jdbc:mysql://localhost:3306/ltdmgdb?zeroDateTimeBehavior=convertToNull","root","");
                String wdt ="insert into days(workingDay,idwd)values(?,?)";
                PreparedStatement pstm = d.prepareStatement(wdt);
                String da3="WednesDay";
                pstm.setString(1, da3);
                pstm.setInt(2, Integer.valueOf(IdentifyKey.getText()));
                pstm.executeUpdate();
                
            }
            else if(!(addWednesday.isSelected())){
                Connection d = DriverManager.getConnection("jdbc:mysql://localhost:3306/ltdmgdb?zeroDateTimeBehavior=convertToNull","root","");
                String wdt ="insert into days(workingDay,idwd)values(?,?)";
                PreparedStatement pstm = d.prepareStatement(wdt);
                String da3="No WednesDay";
                pstm.setString(1, da3);
                pstm.setInt(2, Integer.valueOf(IdentifyKey.getText()));
                pstm.executeUpdate();
            }
            if(addThursday.isSelected()){
                days4 = "Working";
                tot+=1;
                Connection d = DriverManager.getConnection("jdbc:mysql://localhost:3306/ltdmgdb?zeroDateTimeBehavior=convertToNull","root","");
                String wdt ="insert into days(workingDay,idwd)values(?,?)";
                PreparedStatement pstm = d.prepareStatement(wdt);
                String da4="ThursDay";
                pstm.setString(1, da4);
                pstm.setInt(2, Integer.valueOf(IdentifyKey.getText()));
                pstm.executeUpdate();
                
            }
            else if(!(addThursday.isSelected())){
                Connection d = DriverManager.getConnection("jdbc:mysql://localhost:3306/ltdmgdb?zeroDateTimeBehavior=convertToNull","root","");
                String wdt ="insert into days(workingDay,idwd)values(?,?)";
                PreparedStatement pstm = d.prepareStatement(wdt);
                String da4="No ThursDay";
                pstm.setString(1, da4);
                pstm.setInt(2, Integer.valueOf(IdentifyKey.getText()));
                pstm.executeUpdate();
            }
            if(addFriday.isSelected()){
                days5 = "Working";
                tot+=1;
                Connection d = DriverManager.getConnection("jdbc:mysql://localhost:3306/ltdmgdb?zeroDateTimeBehavior=convertToNull","root","");
                String wdt ="insert into days(workingDay,idwd)values(?,?)";
                PreparedStatement pstm = d.prepareStatement(wdt);
                String da5="FriDay";
                pstm.setString(1, da5);
                pstm.setInt(2, Integer.valueOf(IdentifyKey.getText()));
                pstm.executeUpdate();
                
            }
            else if(!(addFriday.isSelected())){
                Connection d = DriverManager.getConnection("jdbc:mysql://localhost:3306/ltdmgdb?zeroDateTimeBehavior=convertToNull","root","");
                String wdt ="insert into days(workingDay,idwd)values(?,?)";
                PreparedStatement pstm = d.prepareStatement(wdt);
                String da5="No FriDay";
                pstm.setString(1, da5);
                pstm.setInt(2, Integer.valueOf(IdentifyKey.getText()));
                pstm.executeUpdate();
            }
            if(addSaturday.isSelected()){
                days6 = "Working";
                tot+=1;
                Connection d = DriverManager.getConnection("jdbc:mysql://localhost:3306/ltdmgdb?zeroDateTimeBehavior=convertToNull","root","");
                String wdt ="insert into days(workingDay,idwd)values(?,?)";
                PreparedStatement pstm = d.prepareStatement(wdt);
                String da6="SaturDay";
                pstm.setString(1, da6);
                pstm.setInt(2, Integer.valueOf(IdentifyKey.getText()));
                pstm.executeUpdate();
                
            }
            else if(!(addSaturday.isSelected())){
                Connection d = DriverManager.getConnection("jdbc:mysql://localhost:3306/ltdmgdb?zeroDateTimeBehavior=convertToNull","root","");
                String wdt ="insert into days(workingDay,idwd)values(?,?)";
                PreparedStatement pstm = d.prepareStatement(wdt);
                String da6="No SaturDay";
                pstm.setString(1, da6);
                pstm.setInt(2, Integer.valueOf(IdentifyKey.getText()));
                pstm.executeUpdate();
            }
            if(addSunday.isSelected()){
                days7 = "Working";
                tot+=1;
                Connection d = DriverManager.getConnection("jdbc:mysql://localhost:3306/ltdmgdb?zeroDateTimeBehavior=convertToNull","root","");
                String wdt ="insert into days(workingDay,idwd)values(?,?)";
                PreparedStatement pstm = d.prepareStatement(wdt);
                String da7="SunDay";
                pstm.setString(1, da7);
                pstm.setInt(2, Integer.valueOf(IdentifyKey.getText()));
                pstm.executeUpdate();
                
            }
            else if(!(addSunday.isSelected())){
                Connection d = DriverManager.getConnection("jdbc:mysql://localhost:3306/ltdmgdb?zeroDateTimeBehavior=convertToNull","root","");
                String wdt ="insert into days(workingDay,idwd)values(?,?)";
                PreparedStatement pstm = d.prepareStatement(wdt);
                String da7="No SunDay";
                pstm.setString(1, da7);
                pstm.setInt(2, Integer.valueOf(IdentifyKey.getText()));
                pstm.executeUpdate();
            }
            
                pstmt.setString(1, days1);
                pstmt.setString(2, days2);
                pstmt.setString(3, days3);
                pstmt.setString(4, days4);
                pstmt.setString(5, days5);
                pstmt.setString(6, days6);
                pstmt.setString(7, days7);
            
            
            
                hours = addHours.getSelectedItem().toString();
                pstmt.setString(8, hours);

                minuts = addMinutes.getSelectedItem().toString();
                pstmt.setString(9, minuts);

                addWd.setSelectedIndex(tot);
                pstmt.setInt(10, tot);
                if(tot== addWd.getSelectedIndex()){
                    errorCompared.setText("System got Calculation of Selected Days!");
                }else{
                    errorCompared.setText("");
                }

                week = addWeek.getSelectedItem().toString();
                pstmt.setString(11, week);

                month = addMonth.getSelectedItem().toString();
                pstmt.setString(12, month);
                
                pstmt.setInt(13, Integer.valueOf(IdentifyKey.getText()));

                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Inserted Successfully!");
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void addTuesdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTuesdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTuesdayActionPerformed

    private void addFridayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFridayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addFridayActionPerformed

    private void addMondayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMondayMouseClicked
        // monday mouse clicked:
        
        tot+=1;
        
        
        switch(tot){
            case 00:
                addWd.setSelectedIndex(0);
                break;
            case 01:
                addWd.setSelectedIndex(1);
                break;
            case 02:
                addWd.setSelectedIndex(2);
                break;
            case 03:
                addWd.setSelectedIndex(3);
                break;
            case 04:
                addWd.setSelectedIndex(4);
                break;
            case 05:
                addWd.setSelectedIndex(5);
                break;
            case 06:
                addWd.setSelectedIndex(6);
                break;
            case 07:
                addWd.setSelectedIndex(7);
                break;
        }
        //testing
    }//GEN-LAST:event_addMondayMouseClicked

    private void addTuesdayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addTuesdayMouseClicked
        // tuesday mouse clicked:
        
        tot+=1;
        switch(tot){
            case 00:
                addWd.setSelectedIndex(0);
                break;
            case 01:
                addWd.setSelectedIndex(1);
                break;
            case 02:
                addWd.setSelectedIndex(2);
                break;
            case 03:
                addWd.setSelectedIndex(3);
                break;
            case 04:
                addWd.setSelectedIndex(4);
                break;
            case 05:
                addWd.setSelectedIndex(5);
                break;
            case 06:
                addWd.setSelectedIndex(6);
                break;
            case 07:
                addWd.setSelectedIndex(7);
                break;
        }
    }//GEN-LAST:event_addTuesdayMouseClicked

    private void addWednesdayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addWednesdayMouseClicked
        // wednesday mouse clicked:
        
        tot+=1;
        switch(tot){
            case 00:
                addWd.setSelectedIndex(0);
                break;
            case 01:
                addWd.setSelectedIndex(1);
                break;
            case 02:
                addWd.setSelectedIndex(2);
                break;
            case 03:
                addWd.setSelectedIndex(3);
                break;
            case 04:
                addWd.setSelectedIndex(4);
                break;
            case 05:
                addWd.setSelectedIndex(5);
                break;
            case 06:
                addWd.setSelectedIndex(6);
                break;
            case 07:
                addWd.setSelectedIndex(7);
                break;
        }
    }//GEN-LAST:event_addWednesdayMouseClicked

    private void addThursdayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addThursdayMouseClicked
        // thursday mouse clicked:
        
        tot+=1;
        switch(tot){
            case 00:
                addWd.setSelectedIndex(0);
                break;
            case 01:
                addWd.setSelectedIndex(1);
                break;
            case 02:
                addWd.setSelectedIndex(2);
                break;
            case 03:
                addWd.setSelectedIndex(3);
                break;
            case 04:
                addWd.setSelectedIndex(4);
                break;
            case 05:
                addWd.setSelectedIndex(5);
                break;
            case 06:
                addWd.setSelectedIndex(6);
                break;
            case 07:
                addWd.setSelectedIndex(7);
                break;
        }
    }//GEN-LAST:event_addThursdayMouseClicked

    private void addFridayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addFridayMouseClicked
        // friday mouse clicked:
        
        tot+=1;
        switch(tot){
            case 00:
                addWd.setSelectedIndex(0);
                break;
            case 01:
                addWd.setSelectedIndex(1);
                break;
            case 02:
                addWd.setSelectedIndex(2);
                break;
            case 03:
                addWd.setSelectedIndex(3);
                break;
            case 04:
                addWd.setSelectedIndex(4);
                break;
            case 05:
                addWd.setSelectedIndex(5);
                break;
            case 06:
                addWd.setSelectedIndex(6);
                break;
            case 07:
                addWd.setSelectedIndex(7);
                break;
        }
    }//GEN-LAST:event_addFridayMouseClicked

    private void addSaturdayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addSaturdayMouseClicked
        // saturday mouse clicked:
        
        tot+=1;
        switch(tot){
            case 00:
                addWd.setSelectedIndex(0);
                break;
            case 01:
                addWd.setSelectedIndex(1);
                break;
            case 02:
                addWd.setSelectedIndex(2);
                break;
            case 03:
                addWd.setSelectedIndex(3);
                break;
            case 04:
                addWd.setSelectedIndex(4);
                break;
            case 05:
                addWd.setSelectedIndex(5);
                break;
            case 06:
                addWd.setSelectedIndex(6);
                break;
            case 07:
                addWd.setSelectedIndex(7);
                break;
        }
    }//GEN-LAST:event_addSaturdayMouseClicked

    private void addSundayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addSundayMouseClicked
        // sunday mouse clicked:
        
        tot+=1;
        switch(tot){
            case 00:
                addWd.setSelectedIndex(0);
                break;
            case 01:
                addWd.setSelectedIndex(1);
                break;
            case 02:
                addWd.setSelectedIndex(2);
                break;
            case 03:
                addWd.setSelectedIndex(3);
                break;
            case 04:
                addWd.setSelectedIndex(4);
                break;
            case 05:
                addWd.setSelectedIndex(5);
                break;
            case 06:
                addWd.setSelectedIndex(6);
                break;
            case 07:
                addWd.setSelectedIndex(7);
                break;
        }
    }//GEN-LAST:event_addSundayMouseClicked

    private void addMondayMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMondayMouseReleased
        // monday mouse released:
        
        
    }//GEN-LAST:event_addMondayMouseReleased

    private void addMondayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMondayMouseExited
        
    }//GEN-LAST:event_addMondayMouseExited

    private void addMondayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMondayMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_addMondayMouseEntered

    private void addMondayMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMondayMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_addMondayMousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // RESET Button:
        tot = 0;
        errorCompared.setText("");
        addMonth.setSelectedIndex(0);
        addWeek.setSelectedIndex(0);
        addWd.setSelectedIndex(0);
        addMonday.setSelected(false);
        addTuesday.setSelected(false);
        addWednesday.setSelected(false);
        addThursday.setSelected(false);
        addFriday.setSelected(false);
        addSaturday.setSelected(false);
        addSunday.setSelected(false);
        addHours.setSelectedIndex(0);
        addMinutes.setSelectedIndex(0);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void IdentifyKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdentifyKeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdentifyKeyActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // Dash Board:
        if(evt.getActionCommand().equals("Dash Board")){
            System.out.println("Return Dash Board");
        }
        close();
        Member3_Dash_Board wd = new Member3_Dash_Board();
        wd.setVisible(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        if(evt.getActionCommand().equals("Dash Board")){
            System.out.println("Return Dash Board");
        }
        close();
        AddLocations wd = new AddLocations();
        wd.setVisible(true);
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // ADD NOT AVAILABLE SESSIONS:
        if(evt.getActionCommand().equals("ADD NOT AVAILABLE SESSIONS")){
            System.out.println("Details Page of Not Available Time");
        }
        close();
        sessionAndNotAvailableTime wd = new sessionAndNotAvailableTime();
        wd.setVisible(true);
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        // Unique Allocation (Non Overlapping):
        if(evt.getActionCommand().equals("")){
            System.out.println("");
        }
        close();
        NotOverlappingTimeAndRoomAllocation wd = new NotOverlappingTimeAndRoomAllocation();
        wd.setVisible(true);
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        //        Consecutive Button
        if(evt.getActionCommand().equals("")){
            System.out.println("");
        }
        close();
        consecutiveTimesAllocation wd = new consecutiveTimesAllocation();
        wd.setVisible(true); 
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddWorkingDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddWorkingDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddWorkingDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddWorkingDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddWorkingDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IdentifyKey;
    private javax.swing.JCheckBox addFriday;
    private javax.swing.JComboBox<String> addHours;
    private javax.swing.JComboBox<String> addMinutes;
    private javax.swing.JCheckBox addMonday;
    private javax.swing.JComboBox<String> addMonth;
    private javax.swing.JCheckBox addSaturday;
    private javax.swing.JCheckBox addSunday;
    private javax.swing.JCheckBox addThursday;
    private javax.swing.JCheckBox addTuesday;
    private javax.swing.JComboBox<String> addWd;
    private javax.swing.JCheckBox addWednesday;
    private javax.swing.JComboBox<String> addWeek;
    private javax.swing.JLabel errorCompared;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    // End of variables declaration//GEN-END:variables
}
